import BackgroundColor from './BackgroundColor'

import ListNumber from './ListNumber'
import Redo from './Redo'
import Save from './Save'
import StrickeThrough from './StrickeThrough' 
import UnderLine from './UnderLine'
import Undo from './Undo'
import Checked from './Checked'
import TextColor from './TextColor'
import Blockquote from './Blockquote'
import Link from './Link'
import TextStyle from './TextStyle'
import Normal from './Normal'
import Event from './Event'
import Position from './Position'
import Temperature from './Temperature'
import Remove from './Remove'
import Audio from './Audio'
import Play from './Play'
import Menu from './Menu'
import Cancel from './Cancel'
import AddImage from './AddImage'
import AddAudio from './AddAudio'
import AddEvent from './AddEvent'
import More from './More'
import Check from './Check'
import Recorder from './Recorder'
import AudioFile from './AudioFile'
import Camera from './Camera'
import PhotoLibrary from './PhotoLibrary'
import Pause from './Pause'
import Trash from './Trash'
import Edit from './Edit'
import AddEdit from './AddEdit'
import Document from './Document'
import Location from './Location'
import Back from './Back'
import Up from './Up'
import Down from './Down'
import LeftArrow from './LeftArrow'
import Search from './Search'
import Heart from './Heart'
import ArrowRight from './ArrowRight'
import ShoppingBag from './ShoppingBag'
import Sort from './Sort'
import Filter from './Filter'
import Circle from './Circle'
import Percel from './Percel'
import Gift from './Gift'
import Dress from './Dress'
import Right from './Right'

const Icons={BackgroundColor,Checked,Blockquote,Temperature,Location,Gift,Dress,Right,
                TextColor,TextStyle,Redo,Save,Pause,Back,Up,Circle,Percel,
                Remove,AddImage,More,ListNumber,Link,PhotoLibrary,Document,
                Audio,AddAudio,Check,AudioFile,StrickeThrough,UnderLine,AddEdit,
                Normal,Event,Position,Play,Menu,AddEvent,Recorder,Camera,Trash,Edit,Down,LeftArrow,
                Sort,Filter,ShoppingBag,Search,Heart,ArrowRight,Cancel,Undo}

export default Icons