export const TO1STEP = 'to1step';
export const TO2STEP = 'to2step';
export const TONEXTSTEP = 'tonextstep';
export const TOBACKSTEP = 'tobackstep';
export const FOCUSEMAIL = 'focusemail';
export const FOCUSPASSWORD = 'focuspassword';
export const FOCUSNAME = 'focusname';
export const FOCUSMOBILE = 'focusmobile';
export const NOTFOCUSEMAIL = 'notfocusemail';
export const NOTFOCUSPASSWORD = 'notfocuspassword';
export const NOTFOCUSNAME = 'notfocusname';
export const NOTFOCUSMOBILE = 'notfocusmobile';
export const LOGINFB = 'loginfb';
export const LOGINGG = 'logingg';
export const LOGINNORMAL = 'loginnormal'
export const LOGOUT = 'logout';
export const LIKE_PRODUCT= 'like_product'
export const REMOVE_LIKE_PRODUCT='remove_like_product'
export const ADD_TO_CART='ADD_TO_CART'
export const REMOVE_FROM_CART='REMOVE_FROM_CART'
export const SWITCH_LANGUAGE='SWITCH_LANGUAGE'